images:
  - 'gcr.io/agendatec-gcp-proyect/agendatec-backend'

availableSecrets:
  secretManager:
    - versionName: 'projects/371160271556/secrets/FIREBASE_API_KEY/versions/latest'
      env: 'FIREBASE_API_KEY'
    - versionName: 'projects/371160271556/secrets/DATABASE_URL/versions/latest'
      env: 'DATABASE_URL'
    - versionName: 'projects/371160271556/secrets/FIREBASE_JSON/versions/latest'
      env: 'FIREBASE_JSON'

options:
  logging: 'CLOUD_LOGGING_ONLY'

steps:
  # Paso 1: Docker build
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Docker Build'
    args: ['build', '-t', 'gcr.io/agendatec-gcp-proyect/agendatec-backend', '.']

  # Paso 2: Docker push to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Docker image to GCR'
    args: ['push', 'gcr.io/agendatec-gcp-proyect/agendatec-backend']

  # Paso 3: Deploy to Cloud Run with the previous docker image and Cloud SQL connection
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy to Cloud Run with Docker image, Cloud SQL connection, and secrets'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'agendatec-backend'
      - '--image'
      - 'gcr.io/agendatec-gcp-proyect/agendatec-backend'
      - '--add-cloudsql-instances=agendatec-gcp-proyect:us-central1:agendatec-database'
      - '--set-secrets=DATABASE_URL=DATABASE_URL:latest'
      - '--set-secrets=FIREBASE_API_KEY=FIREBASE_API_KEY:latest'
      - '--set-secrets=FIREBASE_JSON=FIREBASE_JSON:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'