options:
  logging: 'CLOUD_LOGGING_ONLY'
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/agendatec-gcp-proyect/agendatec-backend', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/agendatec-gcp-proyect/agendatec-backend']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: ['run', 'deploy', 'agendatec-backend',
           '--image', 'gcr.io/agendatec-gcp-proyect/agendatec-backend',
           '--set-secrets', 'mount-path:/usr/src/app/.env=projects/371160271556/secrets/backend-env',
           '--set-secrets', 'mount-path:/usr/src/app/firebase_service_account.json=projects/371160271556/secrets/firebase-json',
           '--region', 'us-central1', '--platform', 'managed',
           '--allow-unauthenticated']
images:
  - 'gcr.io/agendatec-gcp-proyect/agendatec-backend'
