options:
  logging: 'CLOUD_LOGGING_ONLY'
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/agendatec-gcp-proyect/agendatec-backend', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/agendatec-gcp-proyect/agendatec-backend']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: ['run', 'deploy', 'agendatec-backend',
           '--image', 'gcr.io/agendatec-gcp-proyect/agendatec-backend',
           '--region', 'us-central1', '--platform', 'managed',
           '--allow-unauthenticated']
images:
  - 'gcr.io/agendatec-gcp-proyect/agendatec-backend'