images:
  - 'gcr.io/agendatec-gcp-proyect/agendatec-backend'

availableSecrets:
  secretManager:
    - versionName: 'projects/371160271556/secrets/FIREBASE_API_KEY/versions/latest'
      env: 'FIREBASE_API_KEY'
    - versionName: 'projects/371160271556/secrets/DATABASE_URL/versions/latest'
      env: 'DATABASE_URL'
    - versionName: 'projects/371160271556/secrets/FIREBASE_JSON/versions/latest'
      env: 'FIREBASE_JSON'

options:
  logging: 'CLOUD_LOGGING_ONLY'

steps:
  # Paso 0 : Imprimir el secret de Firebase JSON para verificar que se ha montado correctamente
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Print secret file'
    entrypoint: 'bash'
    args: [ '-c', 'echo $$FIREBASE_JSON' ]
    secretEnv: [ 'FIREBASE_JSON' ]

  # Paso 1: Pasar secret y variables de ambiente para luego docker build
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Send secret as argument and build Docker image'
    entrypoint: 'bash'
    args: ['-c', 'docker build -t gcr.io/agendatec-gcp-proyect/agendatec-backend .']
    secretEnv: [ 'FIREBASE_API_KEY', 'DATABASE_URL', 'FIREBASE_JSON' ]

  # Paso 2: Docker push to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Docker image to GCR'
    args: ['push', 'gcr.io/agendatec-gcp-proyect/agendatec-backend']

  # Paso 3: Deploy to Cloud Run with the previous docker image
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy to Cloud Run with Docker image'
    entrypoint: 'gcloud'
    args: ['run', 'deploy', 'agendatec-backend',
           '--image', 'gcr.io/agendatec-gcp-proyect/agendatec-backend',
           '--region', 'us-central1', '--platform', 'managed',
           '--allow-unauthenticated']