images:
  - 'gcr.io/agendatec-gcp-proyect/agendatec-backend'

availableSecrets:
  secretManager:
    - versionName: 'projects/371160271556/secrets/FIREBASE_API_KEY/versions/latest'
      env: 'FIREBASE_API_KEY'
    - versionName: 'projects/371160271556/secrets/DATABASE_URL/versions/latest'
      env: 'DATABASE_URL'
    - versionName: 'projects/371160271556/secrets/FIREBASE_JSON/versions/latest'
      env: 'FIREBASE_JSON'

options:
  logging: 'CLOUD_LOGGING_ONLY'

steps:
  # Paso 1: Docker build with secret
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Docker Build with secret'
    entrypoint: 'bash'
    args: [ '-c', 'mkdir -p /usr/src/app && echo $$FIREBASE_JSON > /usr/src/app/firebase_service_account.json && docker buildx build --secret id=firebase_json,src=/usr/src/app/firebase_service_account.json -t gcr.io/agendatec-gcp-proyect/agendatec-backend .']
    secretEnv: [ 'FIREBASE_API_KEY', 'DATABASE_URL', 'FIREBASE_JSON' ]

  # Paso 2: Docker push to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Docker image to GCR'
    args: ['push', 'gcr.io/agendatec-gcp-proyect/agendatec-backend']

  # Paso 3: Deploy to Cloud Run with the previous docker image
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy to Cloud Run with Docker image'
    entrypoint: 'gcloud'
    args: ['run', 'deploy', 'agendatec-backend',
           '--add-cloudsql-instances=agendatec-gcp-proyect:us-central1:agendatec-database',
           '--image', 'gcr.io/agendatec-gcp-proyect/agendatec-backend',
           '--region', 'us-central1', '--platform', 'managed',
           '--allow-unauthenticated']